**NUMPY**

**4. TO DO TASK**

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

Complete the following Tasks:

In [3]:
import numpy as np

# Task 1: Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty array (2x2):")
print(empty_array)

# Task 2: Initialize an all one array with size 4X2
ones_array = np.ones((4, 2))
print("\nAll ones array (4x2):")
print(ones_array)

# Task 3: Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 7)  # Filling with the value 7 as an example
print("\nArray filled with 7 (3x3):")
print(fill_value_array)

# Task 4: Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])  # Example reference array
zeros_like_array = np.zeros_like(reference_array)
print("\nArray of zeros with same shape as reference array:")
print(zeros_like_array)

# Task 5: Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nArray of ones with same shape as reference array:")
print(ones_like_array)

# Task 6: Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted list to numpy array:")
print(numpy_array)

Empty array (2x2):
[[4.95495970e-310 0.00000000e+000]
 [8.40296355e+118 6.76391259e-310]]

All ones array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of zeros with same shape as reference array:
[[0 0]
 [0 0]]

Array of ones with same shape as reference array:
[[1 1]
 [1 1]]

Converted list to numpy array:
[1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:

In [4]:
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:")
print(array_range)

# Task 2: Create a 3X3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:")
print(matrix_3x3)

# Task 3: Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 identity matrix:")
print(identity_matrix)

# Task 4: Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:")
print(random_array)
print("Mean of the array:")
print(mean_value)

# Task 5: Create a 10X10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 array with random values:")
print(random_10x10)
print("Minimum value:")
print(min_value)
print("Maximum value:")
print(max_value)

# Task 6: Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element replaced by 1:")
print(zero_array)

# Task 7: Reverse an array arr = [1,2,0,0,4,0]
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nReversed array:")
print(reversed_array)

# Task 8: Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))  # Example with 5x5 matrix
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:")
print(border_array)

# Task 9: Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 checkerboard pattern:")
print(checkerboard)

Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
[0.45147705 0.47324253 0.2916476  0.46741616 0.21737901 0.36041011
 0.0638218  0.71560356 0.37900853 0.61770041 0.94380975 0.77172585
 0.3472669  0.57539231 0.79820029 0.76866969 0.83948722 0.69694873
 0.27939539 0.95579738 0.46080715 0.3430102  0.16646279 0.989675
 0.87795097 0.64684914 0.5756651  0.10557866 0.62176565 0.45095188]
Mean of the array:
0.5417705603248586

10x10 array with random values:
[[0.41734391 0.6202371  0.92051317 0.39838419 0.16985848 0.86718103
  0.3428452  0.08094656 0.58630914 0.31003453]
 [0.13501923 0.83426755 0.82016615 0.68889285 0.90498754 0.82033173
  0.95920088 0.39766    0.83215645 0.96406421]
 [0.38395505 0.93386871 0.79364096 0.54716679 0.12142258 0.

Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

In [5]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
addition = x + y
print("Addition of x and y:")
print(addition)

# Task 2: Subtract the two arrays
subtraction = x - y
print("\nSubtraction of x and y:")
print(subtraction)

# Task 3: Multiply the array x with an integer (e.g., 2)
multiplication = x * 2
print("\nMultiplication of x by 2:")
print(multiplication)

# Task 4: Find the square of each element in x
square = np.square(x)
print("\nSquare of each element in x:")
print(square)

# Task 5: Dot product
# Dot product between v and w
dot_vw = np.dot(v, w)
print("\nDot product of v and w:")
print(dot_vw)

# Dot product between x and v
dot_xv = np.dot(x, v)
print("\nDot product of x and v:")
print(dot_xv)

# Dot product between x and y
dot_xy = np.dot(x, y)
print("\nDot product of x and y:")
print(dot_xy)

# Task 6: Concatenate x and y along rows; Concatenate v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)  # Concatenating along rows
concat_vw_col = np.vstack((v, w))  # Concatenating along columns
print("\nConcatenation of x and y along rows:")
print(concat_xy_row)
print("\nConcatenation of v and w along columns:")
print(concat_vw_col)

# Task 7: Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:")
    print(concat_xv)
except ValueError as e:
    print("\nError during concatenation of x and v:")
    print(e)

Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
[[ 2  4]
 [ 6 10]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
[[ 9 10]
 [11 12]]

Error during concatenation of x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

In [7]:
#1. Prove A.A−1 = I.
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute A^-1
A_inv = np.linalg.inv(A)

# Compute A * A^-1
result = np.dot(A, A_inv)
print("A * A^-1 = I (Identity Matrix):")
print(result)

A * A^-1 = I (Identity Matrix):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [8]:
#2. Prove AB ̸= BA.
# Compute AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:")
print(AB)
print("BA:")
print(BA)
print("Is AB equal to BA? ", np.array_equal(AB, BA))


AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Is AB equal to BA?  False


In [10]:
#3. Prove (AB)transpose = B transpose A transpose
# Compute (AB)^T
AB_transpose = np.transpose(AB)

# Compute B^T * A^T
BT_AT = np.dot(B.T, A.T)

print("\n(AB)^T:")
print(AB_transpose)
print("B^T * A^T:")
print(BT_AT)
print("Is (AB)^T equal to B^T * A^T? ", np.array_equal(AB_transpose, BT_AT))



(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T?  True


In [11]:
# Define coefficient matrix A and constant matrix B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)

print("\nSolution of the system of equations using inverse method:")
print("X =", X)


Solution of the system of equations using inverse method:
X = [ 2.  1. -2.]
